services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 10